export const CONSTANTES = {
  // API URLs
  API_URL: "http://localhost:3001/sismoc/api",
  API_IBGE:
    "https://servicodados.ibge.gov.br/api/v1/localidades/estados/<UF>/municipios",
  API_CNAE_GRUPOS: "https://servicodados.ibge.gov.br/api/v2/cnae/grupos",
  ID_IJ_ACT: "I8v4p9XtkXJk9bw96wY4" , // CASO SEJA ALTERADO NO BANCO DE DADOS ALTERAR AQUI TB

  // Botões
  BTN_CANCELAR: "CANCELAR",
  BTN_SALVAR: "SALVAR",
  BTN_NEW_CARGO: "Novo Cargo",
  BTN_NEW_END: "Novo Endereço",

  // Gerais
  VAZIO: "",
  SPACE: " ",
  TITLE_APP: "SISMOC - Sistema de Monitoramento e Controle",
  UNDERLINE: "_",
  INVALID_DATE: "Invalid Date",
  STORAGE_PATH_IJ: "instrumentoJuridico",

  // -------- Página de Cadastro de Parceiro-----------------------------------
  LBL_ENDS: "Endereços",
  LBL_DOC: "Documento",
  LBL_CONTATOS: "Contatos",
  LBL_END: "Endereço",
  LBL_PARC: "Parceiro",
  LBL_CARGOS: "Cargos",
  LBL_LIST: "Lista",
  LBL_NEW_END: "Novo Endereço",
  LBL_NEW_PARC: "Novo Parceiro",
  LBL_NEW_VAG: "Nova Vaga",
  LBL_EDIT_END: "Editar Endereço",
  LBL_EDIT_PARC: "Editar Parceiro",
  LBL_CREATE_PARC: "Cadastrar Parceiro",
  LBL_LIST_PARC: "Lista de Parceiros",
  LBL_TRATATIVA_PARC: "Em Tratativa",
  LBL_CONCLUIDO_PARC: "Concluído",
  LBL_VAG: "Vaga",
  LBL_LIST_VAG: "Lista de Vagas",

  // ------------------------------ Cadastro Contato
  LBL_LOGRADOURO: "Logradouro",
  LBL_NUM: "Nº",
  LBL_COMPL: "Complemento",
  LBL_BAIRRO: "Bairro",
  LBL_CIDADE: "Cidade",
  LBL_UF: "UF",
  LBL_UF_ACTION: "UF da Ação",
  LBL_LOCAL_ASS: "Local da Assinatura",
  LBL_CEP: "CEP",
  LBL_LIST_END: "Lista de Endereços",
  LBL_NAME_PARC: "Nome",
  LBL_SEG_PARC: "Segmento",
  LBL_TYPE_PARC: "Tipo",
  LBL_AREA_PARC: "Área/Tema",
  LBL_CARGO: "Cargo",
  LBL_ESCO: "Escolaridade",
  LBL_CEL: "Celular",
  LBL_EMAIL: "E-mail",
  LBL_PTO_FC_PARC: "Ponto Focal Parceiro",
  LBL_PT_FC_SISEC: "Ponto Focal SISEC",
  LBL_TEL: "Telefone",
  LBL_PARC_ANDAMENTO: "Parceria em Andamento",
  LBL_PROCESSO_PARC: "Processo SEI",
  // -------- Página de Instrumento Jurídico -----------------------------------
  LBL_INST_JUR: "Instrumento Jurídico",
  LBL_TYPE_IJ: "Espécie/Ação",
  LBL_SUBTYPE_IJ: "Subespécie",
  LBL_STATUS_IJ: "Status",
  LBL_SELECT_FILE: "Selecione o Arquivo",
  LBL_OBJ: "Objeto",
  LBL_INFO_ADD: "Informações Adicionais",
  LBL_DT_ASS: "Data Provável da Assinatura",
  LBL_DT_FIM: "Data Fim da Vigência",

  // Cabeçalhos de Tabelas
  TBL_HEAD_LOG: "LOGRADOURO",
  TBL_HEAD_COMPL: "COMPLEMENTO",
  TBL_HEAD_CITY: "CIDADE",
  TBL_HEAD_ESCOL: "ESCOLARIDADE",
  TBL_HEAD_UF: "UF",
  TBL_HEAD_NOME: "NOME",
  TBL_HEAD_SEG: "SEGMENTO",
  TBL_HEAD_TYPE: "TIPO",
  TBL_HEAD_AREA: "ÁREA/TEMA",
  TBL_HEAD_STATS: "STATUS",

  // Lista de Vagas
  TBL_HEAD_PARC: "PARCEIRO",
  TBL_HEAD_CARG: "CARGO",
  TBL_HEAD_POST: "POSTOS",
  
  // Chaves
  KEY_PARC: "parceiroId",
  KEY_CARG: "cargo",
  KEY_POST: "postos",
  KEY_DT_ASS: "dataAssinatura",
  KEY_DT_FIM: "dataFim",
  KEY_LOG_SEL: "logradouroSelecionado",
  KEY_UF_SEL: "ufSelecionada",
  KEY_CID_SEL: "cidadeSelecionada",
  KEY_LOG: "logradouro",
  KEY_COMPL: "complemento",
  KEY_NUM: "numero",
  KEY_BAIRRO: "bairro",
  KEY_CID: "cidade",
  KEY_COD_CID: "codMunicipio",
  KEY_UF: "uf",
  KEY_UF_ACTION: "ufAcao",
  KEY_CEP: "cep",
  KEY_NAME_PARC: "nome",
  KEY_SEG_PARC: "segmento",
  KEY_TYPE_PARC: "tipo",
  KEY_AREA_PARC: "areasAtuacao",
  KEY_TRATATIVA_PARC: "tratativa",
  KEY_DESC: "descricao",
  KEY_OBJ: "objeto",
  KEY_PROCESSO_SEI: "processoSEI",
  KEY_END_PARC: "endereco",
  KEY_STATUS: "status",
  KEY_TYPE_IJ: "tipo",
  KEY_SUBTYPE_IJ: "subtipo",
  KEY_LOCAL_ASS: "localAssinatura",
  KEY_CONTATO: "nome",
  KEY_CARGO: "cargo",
  KEY_EMAIL: "email",
  KEY_CEL: "celular",
  KEY_TEL: "telefone",
  KEY_PT_FC: "pontoFocal",
  KEY_PTO_FC_SISEC: "pontoFocalSISEC",
  KEY_NOME: "nome",
  KEY_SETOR: "setor",
  KEY_PERFIL: "perfil",
  KEY_STATUS_USER: "ativo",
  KEY_TOTAL_INTERESADOS: "Total de Interessados",
  KEY_TOTAL_CANDIDATOS: "Total de Candidatos",
  KEY_TOTAL_NEGATIVAS: "Total de Negativas",
  KEY_DATA_GERACAO: "dataGeracao",
  KEY_DATA_RETORNO: "dataRetorno",
  KEY_DATA_ENVIO: "dataEnvio",
  KEY_MUNICIPIO: "municipio",
  KEY_ARQUIVO: "arquivo",
  KEY_PARCEIRO_SELECIONADO: "parceiro",
  KEY_ATRB: "atribuicoes",
  KEY_PARC2: "parceiro",
  KEY_ENDER: "enderecoSelecionado",
  KEY_ESCOL: "escolaridade",
  KEY_PCD: "pcd",
  KEY_POSTOS: "postos",
  KEY_SALARIO: "salario",
  
  // Mensagens de Seleção
  SELECT_PARC: "Favor selecionar um parceiro",
  SELECT_AREA_ATUACAO: "Favor selecionar área",
  SELECT_TIPO_PARC: "Favor selecionar um tipo",
  SELECT_SEGMENTO_PARC: "Favor selecionar um segmento",
  SELECT_UF: "Favor selecionar uma UF",

  // Mensagens de Erro
  ERROR_UPLOAD_FILE_IJ: "Falha no upload do arquivo de instrumento jurídico",
  ERROR_UF_NOT_FOUND: "A UF não existe!",
  ERROR_FIELD_REQUIRED: "Campo de preenchimento obrigatório",
  ERROR_NUMBER_FIELD:
    "O valor deve ser um número válido entre 1 e 99999, mas não é obrigatório",
  ERROR_FIELD_MAX: "Valor máximo para o campo é 99999",
  ERROR_FIELD_MIN: "Valor mínimo para o campo é 1",
  ERROR_FIELD_MIN_CEP: "Número de CEP inválido",
  ERROR_LIST_END: "Falha ao recuperar a lista de endereços!",
  ERROR_LIST_USER: "Falha ao recuperar a lista de usuários!",
  ERROR_UPDATE_USER: "Falha ao atualizar a lista de usuários!",
  ERROR_DELETE_USER: "Falha ao deletar o usuários!",
  ERROR_ADD_END: "Falha ao criar um novo endereço!",
  ERROR_UPDT_END: "Falha ao atualizar um endereço!",
  ERROR_DEL_END: "Falha ao apagar um endereço!",
  ERROR_GET_CIDADE: "Falha ao recuperar a cidade!",
  ERROR_GET_VAGAS: "Falha ao recuperar as vagas!",
  ERROR_GET_VAGA: "Falha ao recuperar a vaga!",
  ERROR_GET_CARGOS: "Falha ao recuperar os cargos!",
  ERROR_ADD_PARC: "Falha ao criar um novo parceiro!",
  ERROR_UPDT_PARC: "Falha ao atualizar um parceiro!",
  ERROR_DEL_PARC: "Falha ao apagar um parceiro!",
  ERROR_GET_DASH_ANUAL: "Falha ao carregar dados de parceiros!",
  ERROR_LOG_USER: "Falha ao fazer login. Verifique suas credenciais.",
  ERROR_CA_USER:
    "Falha ao cadastrar o usuário. Verifique as informações e tente novamente..",
  ERROR_INVALID_EMAIL: "E-mail inválido.",
  ERROR_INVALID_PERFIL: "Perfil Inválido",
  ERROR_PASSWORD_MIN: "A senha deve ter no mínimo 06 caracteres.",
  ERROR_ADD_USER: "FALHA_ADICIONAR_USUARIO",
  ERROR_ADD_VAGA: "FALHA_ADICIONAR_VAGA",
  ERROR_UPDT_VAGA: "FALHA_ATUALIZAR_VAGA",
  ERROR_GET_PARC: "FALHA_OBTER_PARCEIROS",
  ERROR_GET_ESCOLARIDADES: "FALHA_OBTER_ESCOLARIDADES",
  ERROR_GET_ENDERECOS_BY_PARC: "FALHA_OBTER_ENDERECOS_POR_PARCEIRO",
  ERROR_LIST_TYPE_PARC: "Falha ao obter a lista de tipo de parceiro",
  ERROR_LIST_IJ: "Falha ao obter a lista de instrumentos jurídicos",
  ERROR_LIST_STATUS: "Falha ao obter a lista de status",
  ERROR_LIST_TIPOS: "Falha ao obter a lista de tipos",
  ERROR_LIST_SEG_PARC: "Falha ao obter a lista de segmentos",
  ERROR_LIST_AREA_PARC: "Falha ao obter a lista de áreas de atuação",
  ERROR_LIST_VAGA: "Falha ao obter a lista de vagas",
  ERROR_ADD_IJ: "Falha ao cadastrar um instrumento jurídico",
  ERROR_UPDT_IJ: "Falha ao atualizar um instrumento jurídico",
  ERROR_DEL_IJ: "Falha ao apagar um instrumento jurídico",
  ERROR_DT_FIM_MIN:
    "A data de vigência não pode ser menor que a data da assinatura",
  ERROR_ADICIONAR_LISTA: "Falha ao adicionar a lista.",
  ERROR_LIST_CONTATO: "Falha ao obter a lista de contatos",
  ERROR_ADD_CONTATO: "Falha ao cadastrar um contato",
  ERROR_UPDT_CONTATO: "Falha ao atualizar um contato",
  ERROR_DEL_CONTATO: "Falha ao apagar um contato",
  ERROR_EMAIL_INVALID: "E-mail inválido",
  ERROR_CEL_INVALID: "Nº de celular inválido",
  ERROR_FIELD_DT_INVALID:
    "Data no formato inválido, insira uma data no formato dd/mm/aaaa",
  ERROR_FIELD_DT_GT_CURRENT_DT:
    "A data não pode ser maior que a data atual",
  ERROR_FIELD_DT_LT_CURRENT_DT:
    "A data deve ser maior que a data da assinatura",
  ERROR_UPDATE_STATUS_USER: "Erro ao atualizar o status do usuário!",
  ERROR_UPLOAD_ARQUIVO: "Falha ao fazer upload do arquivo.",
  ERROR_SAVE_FORMULARIO: "Falha ao salvar o formulário.",
  ERROR_MIN_VALUE: "",

  // Mensagens de Sucesso
  SUCCESS_USER_REGISTRADO: "Usuário Registrado com Sucesso.",
  SUC_ADD_VAGA: "VAGA_ADICIONADA",
  SUC_ADD_END: "ENDERECO_ADICIONADO",
  SUCCESS_LISTA_CADASTRADA: "Lista Cadastrada com Sucesso.",

  // Nomes de Campos
  NUM_NAME: "numero",
  DOC_NAME: "documento",
  FILE_NAME: "arquivo",
  END_NAME: "endereco",
  CONTATO_NAME: "contato",
  IJ_NAME: "instrumentoJuridico",
  TYPE_PARC_NAME: "tipoParceiro",
  SEG_NAME: "segmento",
  AREA_NAME: "areaAtuacao",
  PARC_NAME: "parceiroSelecionado",
  VGS_NAME: "vagas",
  TRAB_NAME: "emprego",
  EMPR_NAME: "empreendedorismo",
  CAPCT_NAME: "capacitacao",
  USER_NAME: "usuario",
  EMAIL_NAME: "email",
  SETOR_NAME: "setor",
  PERFIL_NAME: "perfil",
  SENHA_NAME: "senha",
  NOME_NAME: "nome",
  PROC_NAME: "processo",
  OBJ_NAME: "objeto",
  INFO_ADD_NAME: "informacoesAdicionais",
  UF_NAME: "uf",
  NUMERO_INTERESSE_NAME: "numeroDeInteresse",
  CIDADE_NAME: "cidade",
  ARQUIVO_URL_NAME: "arquivoUrl",
  CARGO_NAME: "cargo",
  NUMERO_CANDIDATOS_NAME: "numeroDeCandidatos",
  NUMERO_NEGATIVO_NAME: "numeroDeNegativo",  
  DATA_GERACAO_NAME: "dataGeracao",
  DATA_RETORNO_NAME: "dataRetorno",
  DATA_ENVIO_NAME: "dataEnvio",
  MUNICIPIO_NAME: "municipio",

  // Itens de Menu
  ITEM_MENU_DASH: "Dashboard",
  ITEM_MENU_END: "Endereço",
  ITEM_MENU_PARC: "Parceiro",
  ITEM_MENU_VAG: "Vagas",
  ITEM_MENU_USER: "Usuários",
  ITEM_MENU_LISTAS: "Listas Ouvidoria",

  // Página de Login
  LBL_LO_TITLE: "Login",
  LBL_LO_LOGIN: "Login",
  LBL_LO_EMAIL: "E-mail",
  LBL_LO_PERFIL: "Perfil",
  LBL_LO_SENHA: "Senha",
  LBL_LO_BTN_ENTRAR: "Entrar",

  // Página de Cadastro de Usuário
  LBL_CA_TITLE: "Cadastro de Usuário",
  LBL_CA_NOME: "Nome",
  LBL_CA_EMAIL: "E-mail",
  LBL_CA_SETOR: "Setor",
  LBL_CA_ADM: "Administrador",
  LBL_CA_USER_CO: "Usuário Comum",
  LBL_CA_CADAS: "Cadastrar",
  LBL_CA_USER: "Usuário",
  LBL_CA_DAIT: "DAIT",
  LBL_CA_DAE: "DAE",
  LBL_CA_GABI: "Gabinete",
  LBL_HEAD_NOME: "Nome",
  LBL_HEAD_EMAIL: "E-mail",
  LBL_HEAD_SETOR: "Setor",
  LBL_HEAD_PERFIL: "Perfil",
  LBL_HEAD_STATUS: "Status",
  LBL_HEAD_EDIT: "Editar",
  LBL_LIST_TITLE: "Lista de Usuários",

  // Dashboard
  LBL_EMPRE: "Emprego",
  LBL_EMPREEN: "Empreendedorismo",
  LBL_CAPA: "Capacitação",
  TITLE_DASH_MAPA: "Mapa de Calor",
  TITLE_DASH_LINHA_CONTRA: "Total de Contratados por Ano",
  TITLE_DASH_LINHA_OFER: "Total de Ofertas por Ano",
  TITLE_DASH_TOTAL_PRIV: "Entes Privados",
  TITLE_DASH_TOTAL_PUB: "Entes Públicos",
  TITLE_DASH_TOTAL_ESTA_MUN: "Estados e Municípios",
  TITLE_DASH: "DASHBOARD PARCEIROS",
  TITLE_DASH_TOTAL_VAGAS_OFER: "Ofertas",
  TITLE_DASH_TOTAL_VAGAS_CONTRA: "Contratados",
  CAT_ALL: "all",
  CAT_PRIV: "priv",
  CAT_PUB: "pub",
  FILTER_ANO_2023: "2023",
  FILTER_ANO_2024: "2024",
  FILTER_ANO_2025: "2025",
  FILTER_PRIVADO: "Privado",
  FILTER_PUBLICO: "Público",
  FILTER_ESTADOS_MUNICIPIOS: "Estados e Municípios",
  FILTER_OFERTAS_EMPREGOS: "Ofertas de Emprego",
  FILTER_CONTRATADOS: "Contratados",
  FILTER_JAN: 'Jan',
  FILTER_FEV: 'Fev',
  FILTER_MAR: 'Mar',
  FILTER_ABR: 'Abr',
  FILTER_MAI: 'Mai',
  FILTER_JUN: 'Jun',
  FILTER_JUL: 'Jul',
  FILTER_AGO: 'Ago',
  FILTER_SET: 'Set',
  FILTER_OUT: 'Out',
  FILTER_NOV: 'Nov',
  FILTER_DEC: 'Dec',
  FILTER_ANDAMENTO: 'Andamento',
  FILTER_CONSUMADAS:'Consumidas',

  // -- Página Listas Ouvidoria --
  LBL_LISTAS_OUVI_TITLE: "Cadastrar Informações das Listas",
  LBL_LISTAS_OUVI_TOTAL_CANDIDA: "N° Total de Candidatos",
  LBL_LISTAS_OUVI_TOTAL_INTERE: "Total de Interessados",
  LBL_LISTAS_OUVI_TOTAL_NEGATI: "N° Total Negativas",
  LBL_LISTAS_OUVI_DATA_GERACAO: "Data de Geração",
  LBL_LISTAS_OUVI_DATA_RETORNO: "Data de Retorno",
  LBL_LISTAS_OUVI_COD_MUNI: "Código do Município",
  LBL_LISTAS_OUVI_ARQUIVO: "Selecione o Arquivo",
  LBL_TOTAL_INTERESADOS: "Total de Interessados",
  LBL_LISTAS_OUVI_DATA_ENVIO: "Data de Envio",
  LBL_TOTAL_CANDIDATOS: "Total de Candidatos",
  LBL_LIST_TITLE_LISTAS: "Lista Cadastradas",
  LBL_TOTAL_NEGATIVAS: "Total de Negativas",
  LBL_LISTAS_OUVI_MUNICIPIO: "Município",
  LBL_LISTAS_OUVI_MUNICIDIO: "Município",
  LBL_DATA_GERACAO: "Data de Geração",
  LBL_DATA_RETORNO: "Data de Retorno",
  LBL_DATA_ENVIO: "Data de Envio",
  LBL_MUNICIPIO: "Município",
  LBL_ARQUIVO: "Arquivo",
  LBL_PARCEIRO: "Parceiro",
  ERRO_BUSC_LISTAS: "Falha ao buscar as listas",
  ERROR_DEL_LISTA: "Falha ao deletar a lista",
  ERROR_UPDATE_LISTA: "Falha ao atualizar a lista",
  LBL_ACORDION_VAGAS: "Vagas",
  LBL_ADICIONAR_VAGA: "Adicionar Vaga",
  LBL_VAGA: "Vaga",
  VAGA_SELECIONADA_NAME: "vagaSelecionada",
  SUCCESS_LISTA_ATUALIZADA: "Lista atualizada com sucesso!",

  // Relacionado as Rotas
  ROUT_LISTAS: "/listasOuvidoria",
  ROUTE_END: "/endereco",
  ROUTE_VAG: "/vaga",
  ROUTE_PARC: "/parceiro",
  ROUTE_DASH: "/dashboard",
  ROUTE_USER: "/usuario",
  ROUTE_MAIN: "/",
  ROUTE_ALL: "*",
  ROUTE_LOGIN: "/login",

  // Histórico
  HSTG_END: "endereco",
  HSTG_PARC: "parceiro",
  HSTG_DASH: "dashboard",

  // Índices de Tabs
  TAB_ONE_END: 0,
  TAB_TWO_END: 1,
  TAB_ONE_PARC: 0,
  TAB_TWO_PARC: 1,
  TAB_ONE_USER: 0,
  TAB_TWO_USER: 1,
  TAB_ONE_VAGA: 0,
  TAB_TWO_VAGA: 1,
  TAB_ONE_LISTAS: 0,
  TAB_TWO_LISTAS: 1,

  // Máscaras
  MASK_TEL: "(__) ____-____[0]",
  MASK_CEL: "(__) _____-____",
  MASK_CEP: "_____-___",
  MASK_NUM: "__/____",
  MASK_PROC: "_____.______/____-__",

  // Consultas
  QUERY_ANO_FB: "ano",
  QUERY_MES_FB: "mes",
  QUERY_EQUALS_FB: "==",

  // Meses
  MES_JAN: "Jan",
  MES_FEV: "Fev",
  MES_MAR: "Mar",
  MES_ABR: "Abr",
  MES_MAI: "Mai",
  MES_JUN: "Jun",
  MES_JUL: "Jul",
  MES_AGO: "Ago",
  MES_SET: "Set",
  MES_OUT: "Out",
  MES_NOV: "Nov",
  MES_DEC: "Dec",

  // Coleções
  COL_PARCEIROS_EMPREGO: "dashboard/emprego/parceiros",
  COL_VAGS_EMPREGO: "dashboard/emprego/vagas",

  // Cores
  COR_AZUL: "#1975d1",
  COR_BRANCA: "#FFFFFF",
  SMOOTH_COLOR: "#B8A2CD",
  COR_MENU: "#29252e",

  // Padrões
  PATTERN_MASK: "[-./()]",
  PATTERN_DATE: "DD/MM/YYYY",

  VAGAS_SELECIONADAS_NAME: 'vagasSelecionadas',
};
