import { CONSTANTES } from "./constantes";

export const UFS = [
    { label: 'AC', codIBGE: '12', value: 'Acre'},
    { label: 'AL', codIBGE: '27', value: 'Alagoas'},
    { label: 'AP', codIBGE: '16', value: 'Amapá'},
    { label: 'AM', codIBGE: '13', value: 'Amazonas'},
    { label: 'BA', codIBGE: '29', value: 'Bahia'},
    { label: 'CE', codIBGE: '23', value: 'Ceará'},
    { label: 'DF', codIBGE: '53', value: 'Distrito Federal'},
    { label: 'ES', codIBGE: '32', value: 'Espírito Santo'},
    { label: 'GO', codIBGE: '52', value: 'Goiás'},
    { label: 'MA', codIBGE: '21', value: 'Maranhão'},
    { label: 'MT', codIBGE: '51', value: 'Mato Grosso'},
    { label: 'MS', codIBGE: '50', value: 'Mato Grosso do Sul'},
    { label: 'MG', codIBGE: '31', value: 'Minas Gerais'},
    { label: 'PA', codIBGE: '15', value: 'Pará'},
    { label: 'PB', codIBGE: '25', value: 'Paraíba'},
    { label: 'PR', codIBGE: '41', value: 'Paraná'},
    { label: 'PE', codIBGE: '26', value: 'Pernambuco'},
    { label: 'PI', codIBGE: '22', value: 'Piauí'},
    { label: 'RN', codIBGE: '24', value: 'Rio Grande do Norte'},
    { label: 'RS', codIBGE: '43', value: 'Rio Grande do Sul'},
    { label: 'RJ', codIBGE: '33', value: 'Rio de Janeiro'},
    { label: 'RO', codIBGE: '11', value: 'Rondônia'},
    { label: 'RR', codIBGE: '14', value: 'Roraima'},
    { label: 'SC', codIBGE: '42', value: 'Santa Catarina'},
    { label: 'SP', codIBGE: '35', value: 'São Paulo'},
    { label: 'SE', codIBGE: '28', value: 'Sergipe'},
    { label: 'TO', codIBGE: '17', value: 'Tocantins'},
]